### ISSUE TITLE
engrampa fails to build with new glib2 2.61.2

### ISSUE THREAD

**Issue by david-geiger** [mate-desktop/engrampa#283]
hi,

I tried on Mageia Cauldron (linux) to build engrampa 1.22.1 but it fails to build with recent glib2 2.61.2:

> In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from actions.c:24:
/usr/include/glib-2.0/glib/gtypes.h:551:8: note: declared here
 struct _GTimeVal
        ^~~~~~~~~
In file included from actions.c:43:
glib-utils.h:69:21: error: conflicting types for 'g_ptr_array_copy'
 GPtrArray *         g_ptr_array_copy             (GPtrArray   *array);
                     ^~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:31,
                 from actions.c:24:
/usr/include/glib-2.0/glib/garray.h:141:12: note: previous declaration of 'g_ptr_array_copy' was here
 GPtrArray *g_ptr_array_copy               (GPtrArray        *array,

[build.0.20190812145901.log](https://github.com/mate-desktop/engrampa/files/3536951/build.0.20190812145901.log)

Regards,
David

**Comment by david-geiger** [comment]
The same issue in lxqt-archiver project: https://github.com/lxqt/lxqt-archiver/issues/113

**Comment by david-geiger** [comment]
Thank you! now fixed.

**Comment by lukefromdc** [comment]
I can also verify both the issue and that it is now fixed
